### ISSUE TITLE
Videos aren't download with .mp4 extension

### ISSUE THREAD

**Issue by calscruby1** [macie-k/download-snap-memories#11]
When the files are downloaded, all are assigned the .JPG extension even when the link specifies it's supposed to be a Video .mp4 file.
I was able to just change the extension after downloading but I'm not sure what changed.

**Comment by calscruby1** [comment]
It looks like SnapChat may have changed the text and case of the words contained in the MediaType Tag in the memories_history.json file
With a find and replace in the .json file, the  last exe will still work. 

**Find:** Media Type": "Image"
**Replace:** Media Type": "PHOTO"

**Find:** "Media Type": "Video"
**Replace:** "Media Type": "VIDEO"

Can you take a look and add a check for this in a new release if you find the same?

_extension = '.mp4' if filetype == 'VIDEO' else '.jpg'_
_extension = '.mp4' if filetype == 'Video' else '.jpg'_

**Comment by macie-k** [comment]
Thanks for bringing it up, I checked it myself and it appears that Snapchat indeed changed the media type name
