### ISSUE TITLE
Issues deleting

### ISSUE THREAD

**Issue by alexisjoyr** [macie-k/download-snap-memories#17]
So im trying to delete the application and try again because ive been having issues, and im trying to start over. Everytime i press delete, it disappears, but pops back up when i leave the folder and go back . Pls help, i just want my snap memories back

**Comment by macie-k** [comment]
I don't understand, what reappears?
This is not scripts issue, more like your OS'.

**Comment by alexisjoyr** [comment]
I can’t delete the application, but it is probably the laptop. I was able to get my memories to download by downloading an older version of your app, and it worked despite the deleting issue, so no problems here! thank you so much
