### ISSUE TITLE
Custom JSON file location

### ISSUE THREAD

**Issue by MrMoHanD** [macie-k/download-snap-memories#19]
Hello,
this tool doesn't support custom json file, the file has to be named `memories_history.json` 
so with my little programing experience I was able to add custom json argument to this awesome tool
here is the edit I made and for the developer feel free to add this officially and improve the codding if needed :

### run.py

1. bellow line 12 add this :

>     parser.add_argument('-f', '--file', nargs=1, type=str, help='Select json location')

2. bellow line 20 add this :

>     if args.file: 
>         dm.json_filename = args.file[0]

![1](https://user-images.githubusercontent.com/6288455/180672137-835ccde6-48e0-4b04-bd88-158f3a9b91c3.png)

### download_memories.py

1. bellow line 20 add this :

> json_filename = 'memories_history.json'

![2](https://user-images.githubusercontent.com/6288455/180672143-ca83d7bd-50d4-4f3f-970c-b6f179c1bc43.png)

2. replace line 128 with :

> with open(json_filename, 'r') as f:

![3](https://user-images.githubusercontent.com/6288455/180672141-c1caa64f-2a43-4e0b-a318-250337ed5a6b.png)

### How to use: 
> run.py --dir "./5/" --file "5.json"

**Comment by macie-k** [comment]
I appreciate the effort, but first of all, if you want to suggest your own code changes, you should open a `Pull request` instead of an `Issue`. 

Second of all I really don't see a reason why anyone would rename the JSON file, sorry.

**Comment by MrMoHanD** [comment]
for my case I have multiple json files from multiple snap account 
that make sense to rename each json file with its snap user for example 
user1.json
user2.json
user3.json
and run it with a single run.py 

in the current case of your script you need to create 3 folders with your script in it and on each folder you need to put your memories_history.json file.
