### ISSUE TITLE
Snapchat now allows downloading memories from their data export page

### ISSUE THREAD

**Issue by m5r** [macie-k/download-snap-memories#21]
Go to https://accounts.snapchat.com/accounts/downloadmydata and simply request your data.  
Make sure you tick the checkbox next to `Do you want to include your memories as a downloadable file?`

![image](https://user-images.githubusercontent.com/13026820/206878318-8a3880f3-c85d-4999-9893-d9a796cc82e9.png)

Thanks for your work @macie-k :raised_hands:

**Comment by macie-k** [comment]
Big drawback of using this option is downloading through browser which can be a real bottleneck.
Also it doesn't name the memories properly, which for some people is a must-have.

Anyway thanks for the information, I updated the README and the video description:)

**Comment by m5r** [comment]
That's true, I wish they named the file in a more meaningful way. I don't care about uuids, I want to know when this photo is from. The file's meta doesn't even include this detail...

I noticed a relatively important discrepancy between your tool's export and snapchat's export:  
Snapchat's export contains 5252 memories (file in the form `{uuid}-main.(jpg|mp4)` but when exported without the actual memories, the `memories_history.json` contains 5431 entries. In comparison your tool found 5224 memories from that `memories_history.json` and could download only 4958.

I have no idea which memories were lost or why they were not available. My earliest memory dates from 2016-07-18, maybe some of those files are just too old and were saved differently by snap :man_shrugging:

**Comment by macie-k** [comment]
I didn't actually compare it, but while making this tool I found that many files are just duplicated, meaning they have different uuid, but the same creation time, and are indeed the same file. That might be a reason for the difference in amount.  

You can try downloading the [v1.14.0](https://github.com/macie-k/download-snap-memories/releases/tag/v1.14.0) version, it will show how many duplicates it found, but only after it finishes downloading.

Another way would be to count the difference in snaps before and after removing duplicates in current version, around line 147, if you're feeling adventurous. This will show result instantly.
