### ISSUE TITLE
Issue with downloading snaps

### ISSUE THREAD

**Issue by HRnz-byte** [macie-k/download-snap-memories#6]
Hey there,

Just having a bit of an issue downloading snaps. I will often be able to download between 300-400 snaps before getting some variation of this error, 

'[ERROR] Exception occured: <urlopen error [Errno 11001] getaddrinfo failed'.

I requested a new .json file from snapchat today however that did not appear to make much of a difference.

Any ideas what the problem may be?

Cheers:)

**Comment by emermacko** [comment]
Hi, it's hard to tell just from that.
The `getaddrinfo` error seems to be related directly to the URL that is being opened.
I will request new data and try downloading myself, maybe Snapchat changed something.

Other than that, can you confirm that your internet connection is stable during the download?
Also what OS are you using?

**Comment by emermacko** [comment]
I checked and it seems I don't have that issue, so I will need more information.
If you wish to solve it, download the source `.py` files and add the following line to `download_memories.py`
```python
print(response)
```
On line `56` right before `downloaded = False`

Then type: `pip install -r requirements` in the command line.
And run the script with: `python download_memories.py`

**Comment by alexisjoyr** [comment]
Im having this issue as well :( "exception occurred could not download"

**Comment by alexisjoyr** [comment]
I was able to get it to work by downloading an older version of the application!
