### ISSUE TITLE
[Info] File is detected as a malware by a lot of AV engines.

### ISSUE THREAD

**Issue by KittyJutsu** [macie-k/download-snap-memories#8]
Hey man, your tool is great but it's detected as malware by a lot of engines.

https://www.virustotal.com/gui/file/d8e7bc53364c50ff908c71b77bfab83e64a11859002766321010ee0f6747d5f0/detection

Preferred to let you know in case you didn't.

Have a nice day

**Comment by macie-k** [comment]
Well, it's even mentioned in the README file, code is open so feel free to read it.
